// Code generated by apigen from backend/openapi.json. DO NOT EDIT.

package huudis

import (
	"context"
	"encoding/json"
	"fmt"
	"net/url"
	"strconv"
)

// apigenTransport is the call behind every GeneratedAPI method: the SDK client sends it
// with its own sign-in and unwraps its own response envelope (a few hand-written lines
// in the client, apigenRequest). query is nil or the query string; body is nil (no body)
// or the JSON body. It returns the envelope's data, as JSON.
type apigenTransport interface {
	apigenRequest(ctx context.Context, method, path string, query url.Values, body map[string]any) (json.RawMessage, error)
}

// GeneratedAPI has all 111 feature routes of the Huudis API, one method each
// (generated from the API spec). A method takes the path parameters, then an *<Method>Args
// with the query fields (tagged query) and the JSON body fields (tagged json): required
// fields are plain values, optional ones pointers, slices or maps that nil leaves out,
// and Body passes the whole body. Each returns the response's data as JSON.
type GeneratedAPI struct{ c apigenTransport }

// Ptr returns a pointer to v, for the optional fields of the *Args structs.
func Ptr[T any](v T) *T { return &v }

// AccountAuditArgs are the inputs of GeneratedAPI.AccountAudit.
type AccountAuditArgs struct {
	// Limit is "limit" in the query.
	Limit *int `query:"limit"`

	// Cursor is "cursor" in the query.
	Cursor *string `query:"cursor"`

	// Event is "event" in the query.
	Event *string `query:"event"`

	// Outcome is "outcome" in the query. One of: success, failure, denied.
	Outcome *string `query:"outcome"`

	// Since is "since" in the query.
	Since *string `query:"since"`

	// Until is "until" in the query.
	Until *string `query:"until"`
}

// AccountAudit calls GET /api/v1/account/audit: List audit.
func (a *GeneratedAPI) AccountAudit(ctx context.Context, p *AccountAuditArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountAuditArgs{}
	}
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(*p.Limit))
	}
	if p.Cursor != nil {
		q.Set("cursor", apigenQueryValue(*p.Cursor))
	}
	if p.Event != nil {
		q.Set("event", apigenQueryValue(*p.Event))
	}
	if p.Outcome != nil {
		q.Set("outcome", apigenQueryValue(*p.Outcome))
	}
	if p.Since != nil {
		q.Set("since", apigenQueryValue(*p.Since))
	}
	if p.Until != nil {
		q.Set("until", apigenQueryValue(*p.Until))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/audit", q, nil)
}

// AccountBilling calls GET /api/v1/account/billing: /billing surface for the Huudis dashboard.
func (a *GeneratedAPI) AccountBilling(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/billing", nil, nil)
}

// AccountBillingCancel calls POST /api/v1/account/billing/cancel: Create a cancel.
func (a *GeneratedAPI) AccountBillingCancel(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/billing/cancel", nil, nil)
}

// AccountBillingCheckoutArgs are the inputs of GeneratedAPI.AccountBillingCheckout.
type AccountBillingCheckoutArgs struct {
	// Tier is "tier" in the body, required. One of: pro, business, scale.
	Tier string `json:"tier"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountBillingCheckout calls POST /api/v1/account/billing/checkout: Create a checkout.
func (a *GeneratedAPI) AccountBillingCheckout(ctx context.Context, p *AccountBillingCheckoutArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountBillingCheckoutArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Tier != "" {
		payload["tier"] = p.Tier
	}
	if _, ok := payload["tier"]; !ok {
		return nil, apigenMissing("AccountBillingCheckout", "Tier")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/billing/checkout", nil, payload)
}

// AccountBillingInvoices calls GET /api/v1/account/billing/invoices: List invoices.
func (a *GeneratedAPI) AccountBillingInvoices(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/billing/invoices", nil, nil)
}

// AccountBillingPlans calls GET /api/v1/account/billing/plans: Public to authenticated sessions — no account scope needed since every user sees the same plans.
func (a *GeneratedAPI) AccountBillingPlans(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/billing/plans", nil, nil)
}

// AccountBillingUsage calls GET /api/v1/account/billing/usage: List usage.
func (a *GeneratedAPI) AccountBillingUsage(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/billing/usage", nil, nil)
}

// AccountCancelDeletion calls POST /api/v1/account/cancel-deletion: Create a cancel deletion.
func (a *GeneratedAPI) AccountCancelDeletion(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/cancel-deletion", nil, nil)
}

// AccountConnectedApps calls GET /api/v1/account/connected-apps: Signal = `RefreshToken`, not `OidcConsent`.
func (a *GeneratedAPI) AccountConnectedApps(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/connected-apps", nil, nil)
}

// AccountConnectedAppsRevoke calls POST /api/v1/account/connected-apps/{clientId}/revoke: Revoke every live refresh-token family this user holds for the client.
func (a *GeneratedAPI) AccountConnectedAppsRevoke(ctx context.Context, clientID string) (json.RawMessage, error) {
	path := "/api/v1/account/connected-apps/" + url.PathEscape(clientID) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AccountCreateWebhookSubscriptionsArgs are the inputs of GeneratedAPI.AccountCreateWebhookSubscriptions.
type AccountCreateWebhookSubscriptionsArgs struct {
	// URL is "url" in the body, required.
	URL string `json:"url"`

	// Events is "events" in the body, required.
	Events []string `json:"events"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Active is "active" in the body.
	Active *bool `json:"active,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountCreateWebhookSubscriptions calls POST /api/v1/account/webhook-subscriptions: Create a webhook subscription.
func (a *GeneratedAPI) AccountCreateWebhookSubscriptions(ctx context.Context, p *AccountCreateWebhookSubscriptionsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountCreateWebhookSubscriptionsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.URL != "" {
		payload["url"] = p.URL
	}
	if p.Events != nil {
		payload["events"] = p.Events
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.Active != nil {
		payload["active"] = *p.Active
	}
	if _, ok := payload["url"]; !ok {
		return nil, apigenMissing("AccountCreateWebhookSubscriptions", "URL")
	}
	if _, ok := payload["events"]; !ok {
		return nil, apigenMissing("AccountCreateWebhookSubscriptions", "Events")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/webhook-subscriptions", nil, payload)
}

// AccountCreateWorkspacesArgs are the inputs of GeneratedAPI.AccountCreateWorkspaces.
type AccountCreateWorkspacesArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountCreateWorkspaces calls POST /api/v1/account/workspaces: Create a workspace.
func (a *GeneratedAPI) AccountCreateWorkspaces(ctx context.Context, p *AccountCreateWorkspacesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountCreateWorkspacesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("AccountCreateWorkspaces", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/workspaces", nil, payload)
}

// AccountDeleteArgs are the inputs of GeneratedAPI.AccountDelete.
type AccountDeleteArgs struct {
	// Password is "password" in the body.
	Password *string `json:"password,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountDelete calls DELETE /api/v1/account: Delete account.
func (a *GeneratedAPI) AccountDelete(ctx context.Context, p *AccountDeleteArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountDeleteArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Password != nil {
		payload["password"] = *p.Password
	}
	return a.c.apigenRequest(ctx, "DELETE", "/api/v1/account", nil, payload)
}

// AccountDeleteConnectedApps calls DELETE /api/v1/account/connected-apps/{id}: Legacy consent-id path.
func (a *GeneratedAPI) AccountDeleteConnectedApps(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/connected-apps/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// AccountDeleteLinkedAccounts calls DELETE /api/v1/account/linked-accounts/{provider}: Delete a linked account.
func (a *GeneratedAPI) AccountDeleteLinkedAccounts(ctx context.Context, provider string) (json.RawMessage, error) {
	path := "/api/v1/account/linked-accounts/" + url.PathEscape(provider)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// AccountDeleteSocialProviders calls DELETE /api/v1/account/social-providers/{provider}: Delete a social provider.
func (a *GeneratedAPI) AccountDeleteSocialProviders(ctx context.Context, provider string) (json.RawMessage, error) {
	path := "/api/v1/account/social-providers/" + url.PathEscape(provider)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// AccountDeleteWebhookSubscriptions calls DELETE /api/v1/account/webhook-subscriptions/{id}: Delete a webhook subscription.
func (a *GeneratedAPI) AccountDeleteWebhookSubscriptions(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/webhook-subscriptions/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// AccountEmailChangeArgs are the inputs of GeneratedAPI.AccountEmailChange.
type AccountEmailChangeArgs struct {
	// Email is "email" in the body, required.
	Email string `json:"email"`

	// Password is "password" in the body, required.
	Password string `json:"password"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountEmailChange calls POST /api/v1/account/email-change: Create an email change.
func (a *GeneratedAPI) AccountEmailChange(ctx context.Context, p *AccountEmailChangeArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountEmailChangeArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Email != "" {
		payload["email"] = p.Email
	}
	if p.Password != "" {
		payload["password"] = p.Password
	}
	if _, ok := payload["email"]; !ok {
		return nil, apigenMissing("AccountEmailChange", "Email")
	}
	if _, ok := payload["password"]; !ok {
		return nil, apigenMissing("AccountEmailChange", "Password")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/email-change", nil, payload)
}

// AccountLinkedAccounts calls GET /api/v1/account/linked-accounts: List linked accounts.
func (a *GeneratedAPI) AccountLinkedAccounts(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/linked-accounts", nil, nil)
}

// AccountList calls GET /api/v1/account: List account.
func (a *GeneratedAPI) AccountList(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account", nil, nil)
}

// AccountPasswordChangeArgs are the inputs of GeneratedAPI.AccountPasswordChange.
type AccountPasswordChangeArgs struct {
	// CurrentPassword is "currentPassword" in the body.
	CurrentPassword *string `json:"currentPassword,omitempty"`

	// NewPassword is "newPassword" in the body, required.
	NewPassword string `json:"newPassword"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountPasswordChange calls POST /api/v1/account/password-change: Create a password change.
func (a *GeneratedAPI) AccountPasswordChange(ctx context.Context, p *AccountPasswordChangeArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountPasswordChangeArgs{}
	}
	payload := apigenBody(p.Body)
	if p.CurrentPassword != nil {
		payload["currentPassword"] = *p.CurrentPassword
	}
	if p.NewPassword != "" {
		payload["newPassword"] = p.NewPassword
	}
	if _, ok := payload["newPassword"]; !ok {
		return nil, apigenMissing("AccountPasswordChange", "NewPassword")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/password-change", nil, payload)
}

// AccountScheduleDeletionArgs are the inputs of GeneratedAPI.AccountScheduleDeletion.
type AccountScheduleDeletionArgs struct {
	// Password is "password" in the body.
	Password *string `json:"password,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountScheduleDeletion calls POST /api/v1/account/schedule-deletion: Self-serve soft-delete: stamps a 30-day grace marker.
func (a *GeneratedAPI) AccountScheduleDeletion(ctx context.Context, p *AccountScheduleDeletionArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountScheduleDeletionArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Password != nil {
		payload["password"] = *p.Password
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/schedule-deletion", nil, payload)
}

// AccountServices calls GET /api/v1/account/services: List services.
func (a *GeneratedAPI) AccountServices(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/services", nil, nil)
}

// AccountServicesDisableArgs are the inputs of GeneratedAPI.AccountServicesDisable.
type AccountServicesDisableArgs struct {
	// Services is "services" in the body, required.
	Services []string `json:"services"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountServicesDisable calls POST /api/v1/account/services/disable: Create a disable.
func (a *GeneratedAPI) AccountServicesDisable(ctx context.Context, p *AccountServicesDisableArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountServicesDisableArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Services != nil {
		payload["services"] = p.Services
	}
	if _, ok := payload["services"]; !ok {
		return nil, apigenMissing("AccountServicesDisable", "Services")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/services/disable", nil, payload)
}

// AccountServicesEnableArgs are the inputs of GeneratedAPI.AccountServicesEnable.
type AccountServicesEnableArgs struct {
	// Services is "services" in the body, required.
	Services []string `json:"services"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountServicesEnable calls POST /api/v1/account/services/enable: Create an enable.
func (a *GeneratedAPI) AccountServicesEnable(ctx context.Context, p *AccountServicesEnableArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountServicesEnableArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Services != nil {
		payload["services"] = p.Services
	}
	if _, ok := payload["services"]; !ok {
		return nil, apigenMissing("AccountServicesEnable", "Services")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/services/enable", nil, payload)
}

// AccountSessions calls GET /api/v1/account/sessions: List sessions.
func (a *GeneratedAPI) AccountSessions(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/sessions", nil, nil)
}

// AccountSessionsRevoke calls POST /api/v1/account/sessions/{id}/revoke: Revoke a session.
func (a *GeneratedAPI) AccountSessionsRevoke(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/sessions/" + url.PathEscape(id) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AccountSessionsRevokeAll calls POST /api/v1/account/sessions/revoke-all: Create a revoke all.
func (a *GeneratedAPI) AccountSessionsRevokeAll(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "POST", "/api/v1/account/sessions/revoke-all", nil, nil)
}

// AccountSetSocialProvidersArgs are the inputs of GeneratedAPI.AccountSetSocialProviders.
type AccountSetSocialProvidersArgs struct {
	// ClientID is "clientId" in the body, required.
	ClientID string `json:"clientId"`

	// Secret is "secret" in the body.
	Secret *string `json:"secret,omitempty"`

	// RedirectURI is "redirectUri" in the body.
	RedirectURI *string `json:"redirectUri,omitempty"`

	// TeamID is "teamId" in the body.
	TeamID *string `json:"teamId,omitempty"`

	// KeyID is "keyId" in the body.
	KeyID *string `json:"keyId,omitempty"`

	// Enabled is "enabled" in the body.
	Enabled *bool `json:"enabled,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountSetSocialProviders calls PUT /api/v1/account/social-providers/{provider}: Replace a social provider.
func (a *GeneratedAPI) AccountSetSocialProviders(ctx context.Context, provider string, p *AccountSetSocialProvidersArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountSetSocialProvidersArgs{}
	}
	payload := apigenBody(p.Body)
	if p.ClientID != "" {
		payload["clientId"] = p.ClientID
	}
	if p.Secret != nil {
		payload["secret"] = *p.Secret
	}
	if p.RedirectURI != nil {
		payload["redirectUri"] = *p.RedirectURI
	}
	if p.TeamID != nil {
		payload["teamId"] = *p.TeamID
	}
	if p.KeyID != nil {
		payload["keyId"] = *p.KeyID
	}
	if p.Enabled != nil {
		payload["enabled"] = *p.Enabled
	}
	if _, ok := payload["clientId"]; !ok {
		return nil, apigenMissing("AccountSetSocialProviders", "ClientID")
	}
	path := "/api/v1/account/social-providers/" + url.PathEscape(provider)
	return a.c.apigenRequest(ctx, "PUT", path, nil, payload)
}

// AccountSocialProviders calls GET /api/v1/account/social-providers: List social providers.
func (a *GeneratedAPI) AccountSocialProviders(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/social-providers", nil, nil)
}

// AccountUpdateArgs are the inputs of GeneratedAPI.AccountUpdate.
type AccountUpdateArgs struct {
	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Locale is "locale" in the body.
	Locale *string `json:"locale,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountUpdate calls PATCH /api/v1/account: Update account.
func (a *GeneratedAPI) AccountUpdate(ctx context.Context, p *AccountUpdateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountUpdateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.Locale != nil {
		payload["locale"] = *p.Locale
	}
	return a.c.apigenRequest(ctx, "PATCH", "/api/v1/account", nil, payload)
}

// AccountUpdateWebhookSubscriptionsArgs are the inputs of GeneratedAPI.AccountUpdateWebhookSubscriptions.
type AccountUpdateWebhookSubscriptionsArgs struct {
	// URL is "url" in the body.
	URL *string `json:"url,omitempty"`

	// Events is "events" in the body.
	Events []string `json:"events,omitempty"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Active is "active" in the body.
	Active *bool `json:"active,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountUpdateWebhookSubscriptions calls PATCH /api/v1/account/webhook-subscriptions/{id}: Update a webhook subscription.
func (a *GeneratedAPI) AccountUpdateWebhookSubscriptions(ctx context.Context, id string, p *AccountUpdateWebhookSubscriptionsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountUpdateWebhookSubscriptionsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.URL != nil {
		payload["url"] = *p.URL
	}
	if p.Events != nil {
		payload["events"] = p.Events
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.Active != nil {
		payload["active"] = *p.Active
	}
	path := "/api/v1/account/webhook-subscriptions/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// AccountUpdateWorkspacesArgs are the inputs of GeneratedAPI.AccountUpdateWorkspaces.
type AccountUpdateWorkspacesArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AccountUpdateWorkspaces calls PATCH /api/v1/account/workspaces/{id}: Update a workspace.
func (a *GeneratedAPI) AccountUpdateWorkspaces(ctx context.Context, id string, p *AccountUpdateWorkspacesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountUpdateWorkspacesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("AccountUpdateWorkspaces", "Name")
	}
	path := "/api/v1/account/workspaces/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// AccountWebhookSubscriptions calls GET /api/v1/account/webhook-subscriptions: List webhook subscriptions.
func (a *GeneratedAPI) AccountWebhookSubscriptions(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/webhook-subscriptions", nil, nil)
}

// AccountWebhookSubscriptions2 calls GET /api/v1/account/webhook-subscriptions/{id}: Get a webhook subscription.
func (a *GeneratedAPI) AccountWebhookSubscriptions2(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/webhook-subscriptions/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// AccountWebhookSubscriptionsDeliveriesArgs are the inputs of GeneratedAPI.AccountWebhookSubscriptionsDeliveries.
type AccountWebhookSubscriptionsDeliveriesArgs struct {
	// Limit is "limit" in the query.
	Limit any `query:"limit"`

	// Status is "status" in the query.
	Status any `query:"status"`
}

// AccountWebhookSubscriptionsDeliveries calls GET /api/v1/account/webhook-subscriptions/{id}/deliveries: List deliveries.
func (a *GeneratedAPI) AccountWebhookSubscriptionsDeliveries(ctx context.Context, id string, p *AccountWebhookSubscriptionsDeliveriesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AccountWebhookSubscriptionsDeliveriesArgs{}
	}
	q := url.Values{}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(p.Limit))
	}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(p.Status))
	}
	path := "/api/v1/account/webhook-subscriptions/" + url.PathEscape(id) + "/deliveries"
	return a.c.apigenRequest(ctx, "GET", path, q, nil)
}

// AccountWebhookSubscriptionsDeliveriesReplay calls POST /api/v1/account/webhook-subscriptions/deliveries/{id}/replay: Replay a delivery.
func (a *GeneratedAPI) AccountWebhookSubscriptionsDeliveriesReplay(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/webhook-subscriptions/deliveries/" + url.PathEscape(id) + "/replay"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AccountWebhookSubscriptionsEventsCatalog calls GET /api/v1/account/webhook-subscriptions/events/catalog: List catalog.
func (a *GeneratedAPI) AccountWebhookSubscriptionsEventsCatalog(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/webhook-subscriptions/events/catalog", nil, nil)
}

// AccountWebhookSubscriptionsRotateSecret calls POST /api/v1/account/webhook-subscriptions/{id}/rotate-secret: Rotate secret a webhook subscription.
func (a *GeneratedAPI) AccountWebhookSubscriptionsRotateSecret(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/webhook-subscriptions/" + url.PathEscape(id) + "/rotate-secret"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AccountWorkspaces calls GET /api/v1/account/workspaces: List workspaces.
func (a *GeneratedAPI) AccountWorkspaces(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/account/workspaces", nil, nil)
}

// AccountWorkspacesCancelDeletion calls POST /api/v1/account/workspaces/{id}/cancel-deletion: Cancel deletion a workspace.
func (a *GeneratedAPI) AccountWorkspacesCancelDeletion(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/workspaces/" + url.PathEscape(id) + "/cancel-deletion"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AccountWorkspacesMembers calls GET /api/v1/account/workspaces/{id}/members: Additive, read-only.
func (a *GeneratedAPI) AccountWorkspacesMembers(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/workspaces/" + url.PathEscape(id) + "/members"
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// AccountWorkspacesScheduleDeletion calls POST /api/v1/account/workspaces/{id}/schedule-deletion: Owner-only soft-delete: stamps a 30-day grace marker on the workspace.
func (a *GeneratedAPI) AccountWorkspacesScheduleDeletion(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/workspaces/" + url.PathEscape(id) + "/schedule-deletion"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AccountWorkspacesSwitch calls POST /api/v1/account/workspaces/{id}/switch: Switch a workspace.
func (a *GeneratedAPI) AccountWorkspacesSwitch(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/account/workspaces/" + url.PathEscape(id) + "/switch"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// AppOverview calls GET /api/v1/app/overview: One row per OIDC client that has ever minted a refresh token: distinct users, 30-day signups, last signup + last activity.
func (a *GeneratedAPI) AppOverview(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/app/overview", nil, nil)
}

// AppStatsArgs are the inputs of GeneratedAPI.AppStats.
type AppStatsArgs struct {
	// Q is "q" in the query.
	Q *string `query:"q"`

	// Status is "status" in the query. One of: all, active, disabled.
	Status *string `query:"status"`

	// Limit is "limit" in the query.
	Limit *int `query:"limit"`

	// ClientID is "clientId" in the query.
	ClientID *string `query:"clientId"`
}

// AppStats calls GET /api/v1/app/stats: List stats.
func (a *GeneratedAPI) AppStats(ctx context.Context, p *AppStatsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AppStatsArgs{}
	}
	q := url.Values{}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(*p.Q))
	}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(*p.Status))
	}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(*p.Limit))
	}
	if p.ClientID != nil {
		q.Set("clientId", apigenQueryValue(*p.ClientID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/app/stats", q, nil)
}

// AppUsersArgs are the inputs of GeneratedAPI.AppUsers.
type AppUsersArgs struct {
	// Q is "q" in the query.
	Q *string `query:"q"`

	// Status is "status" in the query. One of: all, active, disabled.
	Status *string `query:"status"`

	// Limit is "limit" in the query.
	Limit *int `query:"limit"`

	// ClientID is "clientId" in the query.
	ClientID *string `query:"clientId"`
}

// AppUsers calls GET /api/v1/app/users: List users.
func (a *GeneratedAPI) AppUsers(ctx context.Context, p *AppUsersArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AppUsersArgs{}
	}
	q := url.Values{}
	if p.Q != nil {
		q.Set("q", apigenQueryValue(*p.Q))
	}
	if p.Status != nil {
		q.Set("status", apigenQueryValue(*p.Status))
	}
	if p.Limit != nil {
		q.Set("limit", apigenQueryValue(*p.Limit))
	}
	if p.ClientID != nil {
		q.Set("clientId", apigenQueryValue(*p.ClientID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/app/users", q, nil)
}

// AppWorkspacesArgs are the inputs of GeneratedAPI.AppWorkspaces.
type AppWorkspacesArgs struct {
	// IDs is "ids" in the query, required.
	IDs string `query:"ids"`
}

// AppWorkspaces calls GET /api/v1/app/workspaces: List workspaces.
func (a *GeneratedAPI) AppWorkspaces(ctx context.Context, p *AppWorkspacesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AppWorkspacesArgs{}
	}
	q := url.Values{}
	q.Set("ids", p.IDs)
	return a.c.apigenRequest(ctx, "GET", "/api/v1/app/workspaces", q, nil)
}

// AuthzAssumeRoleArgs are the inputs of GeneratedAPI.AuthzAssumeRole.
type AuthzAssumeRoleArgs struct {
	// RoleID is "roleId" in the body, required.
	RoleID string `json:"roleId"`

	// SessionName is "sessionName" in the body.
	SessionName *string `json:"sessionName,omitempty"`

	// DurationSeconds is "durationSeconds" in the body.
	DurationSeconds *int `json:"durationSeconds,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AuthzAssumeRole calls POST /api/v1/authz/assume-role: Create an assume role.
func (a *GeneratedAPI) AuthzAssumeRole(ctx context.Context, p *AuthzAssumeRoleArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AuthzAssumeRoleArgs{}
	}
	payload := apigenBody(p.Body)
	if p.RoleID != "" {
		payload["roleId"] = p.RoleID
	}
	if p.SessionName != nil {
		payload["sessionName"] = *p.SessionName
	}
	if p.DurationSeconds != nil {
		payload["durationSeconds"] = *p.DurationSeconds
	}
	if _, ok := payload["roleId"]; !ok {
		return nil, apigenMissing("AuthzAssumeRole", "RoleID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/authz/assume-role", nil, payload)
}

// AuthzCheckArgs are the inputs of GeneratedAPI.AuthzCheck.
type AuthzCheckArgs struct {
	// Principal is "principal" in the body, required.
	Principal map[string]any `json:"principal"`

	// Action is "action" in the body, required.
	Action string `json:"action"`

	// Resource is "resource" in the body, required.
	Resource string `json:"resource"`

	// Context is "context" in the body.
	Context map[string]any `json:"context,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// AuthzCheck calls POST /api/v1/authz/check: Create a check.
func (a *GeneratedAPI) AuthzCheck(ctx context.Context, p *AuthzCheckArgs) (json.RawMessage, error) {
	if p == nil {
		p = &AuthzCheckArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Principal != nil {
		payload["principal"] = p.Principal
	}
	if p.Action != "" {
		payload["action"] = p.Action
	}
	if p.Resource != "" {
		payload["resource"] = p.Resource
	}
	if p.Context != nil {
		payload["context"] = p.Context
	}
	if _, ok := payload["principal"]; !ok {
		return nil, apigenMissing("AuthzCheck", "Principal")
	}
	if _, ok := payload["action"]; !ok {
		return nil, apigenMissing("AuthzCheck", "Action")
	}
	if _, ok := payload["resource"]; !ok {
		return nil, apigenMissing("AuthzCheck", "Resource")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/authz/check", nil, payload)
}

// AuthzWhoami calls GET /api/v1/authz/whoami: Session-auth health ping so dashboard can verify reachability.
func (a *GeneratedAPI) AuthzWhoami(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/authz/whoami", nil, nil)
}

// IamAccessKeysArgs are the inputs of GeneratedAPI.IamAccessKeys.
type IamAccessKeysArgs struct {
	// PrincipalType is "principalType" in the query, required. One of: user, service_account.
	PrincipalType string `query:"principalType"`

	// PrincipalID is "principalId" in the query, required.
	PrincipalID string `query:"principalId"`
}

// IamAccessKeys calls GET /api/v1/iam/access-keys: List access keys.
func (a *GeneratedAPI) IamAccessKeys(ctx context.Context, p *IamAccessKeysArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamAccessKeysArgs{}
	}
	q := url.Values{}
	q.Set("principalType", p.PrincipalType)
	q.Set("principalId", p.PrincipalID)
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/access-keys", q, nil)
}

// IamAccessKeysRevoke calls POST /api/v1/iam/access-keys/{id}/revoke: Revoke an access key.
func (a *GeneratedAPI) IamAccessKeysRevoke(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/access-keys/" + url.PathEscape(id) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// IamAssumedSessions calls GET /api/v1/iam/assumed-sessions: List assumed sessions.
func (a *GeneratedAPI) IamAssumedSessions(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/assumed-sessions", nil, nil)
}

// IamAssumedSessionsRevoke calls POST /api/v1/iam/assumed-sessions/{id}/revoke: Revoke an assumed session.
func (a *GeneratedAPI) IamAssumedSessionsRevoke(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/assumed-sessions/" + url.PathEscape(id) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// IamCreateAccessKeysArgs are the inputs of GeneratedAPI.IamCreateAccessKeys.
type IamCreateAccessKeysArgs struct {
	// PrincipalType is "principalType" in the body, required. One of: user, service_account.
	PrincipalType string `json:"principalType"`

	// PrincipalID is "principalId" in the body, required.
	PrincipalID string `json:"principalId"`

	// Label is "label" in the body.
	Label *string `json:"label,omitempty"`

	// ExpiresAt is "expiresAt" in the body.
	ExpiresAt *string `json:"expiresAt,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateAccessKeys calls POST /api/v1/iam/access-keys: Create an access key.
func (a *GeneratedAPI) IamCreateAccessKeys(ctx context.Context, p *IamCreateAccessKeysArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateAccessKeysArgs{}
	}
	payload := apigenBody(p.Body)
	if p.PrincipalType != "" {
		payload["principalType"] = p.PrincipalType
	}
	if p.PrincipalID != "" {
		payload["principalId"] = p.PrincipalID
	}
	if p.Label != nil {
		payload["label"] = *p.Label
	}
	if p.ExpiresAt != nil {
		payload["expiresAt"] = *p.ExpiresAt
	}
	if _, ok := payload["principalType"]; !ok {
		return nil, apigenMissing("IamCreateAccessKeys", "PrincipalType")
	}
	if _, ok := payload["principalId"]; !ok {
		return nil, apigenMissing("IamCreateAccessKeys", "PrincipalID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/access-keys", nil, payload)
}

// IamCreateGroupsArgs are the inputs of GeneratedAPI.IamCreateGroups.
type IamCreateGroupsArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateGroups calls POST /api/v1/iam/groups: Create a group.
func (a *GeneratedAPI) IamCreateGroups(ctx context.Context, p *IamCreateGroupsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateGroupsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("IamCreateGroups", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/groups", nil, payload)
}

// IamCreateGroupsMembersArgs are the inputs of GeneratedAPI.IamCreateGroupsMembers.
type IamCreateGroupsMembersArgs struct {
	// UserID is "userId" in the body, required.
	UserID string `json:"userId"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateGroupsMembers calls POST /api/v1/iam/groups/{id}/members: Members a group.
func (a *GeneratedAPI) IamCreateGroupsMembers(ctx context.Context, id string, p *IamCreateGroupsMembersArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateGroupsMembersArgs{}
	}
	payload := apigenBody(p.Body)
	if p.UserID != "" {
		payload["userId"] = p.UserID
	}
	if _, ok := payload["userId"]; !ok {
		return nil, apigenMissing("IamCreateGroupsMembers", "UserID")
	}
	path := "/api/v1/iam/groups/" + url.PathEscape(id) + "/members"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// IamCreateIdentityProvidersArgs are the inputs of GeneratedAPI.IamCreateIdentityProviders.
type IamCreateIdentityProvidersArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Type is "type" in the body, required. One of: saml, oidc.
	Type string `json:"type"`

	// Metadata is "metadata" in the body.
	Metadata map[string]any `json:"metadata,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateIdentityProviders calls POST /api/v1/iam/identity-providers: Create an identity provider.
func (a *GeneratedAPI) IamCreateIdentityProviders(ctx context.Context, p *IamCreateIdentityProvidersArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateIdentityProvidersArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Type != "" {
		payload["type"] = p.Type
	}
	if p.Metadata != nil {
		payload["metadata"] = p.Metadata
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("IamCreateIdentityProviders", "Name")
	}
	if _, ok := payload["type"]; !ok {
		return nil, apigenMissing("IamCreateIdentityProviders", "Type")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/identity-providers", nil, payload)
}

// IamCreateInvitesArgs are the inputs of GeneratedAPI.IamCreateInvites.
type IamCreateInvitesArgs struct {
	// Email is "email" in the body, required.
	Email string `json:"email"`

	// Role is "role" in the body. One of: owner, admin, member.
	Role *string `json:"role,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateInvites calls POST /api/v1/iam/invites: Create an invite.
func (a *GeneratedAPI) IamCreateInvites(ctx context.Context, p *IamCreateInvitesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateInvitesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Email != "" {
		payload["email"] = p.Email
	}
	if p.Role != nil {
		payload["role"] = *p.Role
	}
	if _, ok := payload["email"]; !ok {
		return nil, apigenMissing("IamCreateInvites", "Email")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/invites", nil, payload)
}

// IamCreatePoliciesArgs are the inputs of GeneratedAPI.IamCreatePolicies.
type IamCreatePoliciesArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Document is "document" in the body, required.
	Document map[string]any `json:"document"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreatePolicies calls POST /api/v1/iam/policies: Create a policy.
func (a *GeneratedAPI) IamCreatePolicies(ctx context.Context, p *IamCreatePoliciesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreatePoliciesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.Document != nil {
		payload["document"] = p.Document
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("IamCreatePolicies", "Name")
	}
	if _, ok := payload["document"]; !ok {
		return nil, apigenMissing("IamCreatePolicies", "Document")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/policies", nil, payload)
}

// IamCreatePolicyAttachmentsArgs are the inputs of GeneratedAPI.IamCreatePolicyAttachments.
type IamCreatePolicyAttachmentsArgs struct {
	// PolicyID is "policyId" in the body, required.
	PolicyID string `json:"policyId"`

	// PrincipalType is "principalType" in the body, required. One of: user, group, role, service_account.
	PrincipalType string `json:"principalType"`

	// PrincipalID is "principalId" in the body, required.
	PrincipalID string `json:"principalId"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreatePolicyAttachments calls POST /api/v1/iam/policy-attachments: Create a policy attachment.
func (a *GeneratedAPI) IamCreatePolicyAttachments(ctx context.Context, p *IamCreatePolicyAttachmentsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreatePolicyAttachmentsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.PolicyID != "" {
		payload["policyId"] = p.PolicyID
	}
	if p.PrincipalType != "" {
		payload["principalType"] = p.PrincipalType
	}
	if p.PrincipalID != "" {
		payload["principalId"] = p.PrincipalID
	}
	if _, ok := payload["policyId"]; !ok {
		return nil, apigenMissing("IamCreatePolicyAttachments", "PolicyID")
	}
	if _, ok := payload["principalType"]; !ok {
		return nil, apigenMissing("IamCreatePolicyAttachments", "PrincipalType")
	}
	if _, ok := payload["principalId"]; !ok {
		return nil, apigenMissing("IamCreatePolicyAttachments", "PrincipalID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/policy-attachments", nil, payload)
}

// IamCreateRolesArgs are the inputs of GeneratedAPI.IamCreateRoles.
type IamCreateRolesArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// TrustPolicy is "trustPolicy" in the body, required.
	TrustPolicy map[string]any `json:"trustPolicy"`

	// MaxSessionDurationSec is "maxSessionDurationSec" in the body.
	MaxSessionDurationSec *int `json:"maxSessionDurationSec,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateRoles calls POST /api/v1/iam/roles: Create a role.
func (a *GeneratedAPI) IamCreateRoles(ctx context.Context, p *IamCreateRolesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateRolesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.TrustPolicy != nil {
		payload["trustPolicy"] = p.TrustPolicy
	}
	if p.MaxSessionDurationSec != nil {
		payload["maxSessionDurationSec"] = *p.MaxSessionDurationSec
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("IamCreateRoles", "Name")
	}
	if _, ok := payload["trustPolicy"]; !ok {
		return nil, apigenMissing("IamCreateRoles", "TrustPolicy")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/roles", nil, payload)
}

// IamCreateServiceAccountsArgs are the inputs of GeneratedAPI.IamCreateServiceAccounts.
type IamCreateServiceAccountsArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateServiceAccounts calls POST /api/v1/iam/service-accounts: Create a service account.
func (a *GeneratedAPI) IamCreateServiceAccounts(ctx context.Context, p *IamCreateServiceAccountsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateServiceAccountsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("IamCreateServiceAccounts", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/service-accounts", nil, payload)
}

// IamCreateUsersArgs are the inputs of GeneratedAPI.IamCreateUsers.
type IamCreateUsersArgs struct {
	// Email is "email" in the body, required.
	Email string `json:"email"`

	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Password is "password" in the body.
	Password *string `json:"password,omitempty"`

	// Role is "role" in the body. One of: owner, admin, member.
	Role *string `json:"role,omitempty"`

	// EmailVerified is "emailVerified" in the body.
	EmailVerified *bool `json:"emailVerified,omitempty"`

	// SendInviteEmail is "sendInviteEmail" in the body.
	SendInviteEmail *bool `json:"sendInviteEmail,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamCreateUsers calls POST /api/v1/iam/users: Create an user.
func (a *GeneratedAPI) IamCreateUsers(ctx context.Context, p *IamCreateUsersArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamCreateUsersArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Email != "" {
		payload["email"] = p.Email
	}
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.Password != nil {
		payload["password"] = *p.Password
	}
	if p.Role != nil {
		payload["role"] = *p.Role
	}
	if p.EmailVerified != nil {
		payload["emailVerified"] = *p.EmailVerified
	}
	if p.SendInviteEmail != nil {
		payload["sendInviteEmail"] = *p.SendInviteEmail
	}
	if _, ok := payload["email"]; !ok {
		return nil, apigenMissing("IamCreateUsers", "Email")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/iam/users", nil, payload)
}

// IamDeleteAccessKeys calls DELETE /api/v1/iam/access-keys/{id}: Delete an access key.
func (a *GeneratedAPI) IamDeleteAccessKeys(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/access-keys/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeleteGroups calls DELETE /api/v1/iam/groups/{id}: Delete a group.
func (a *GeneratedAPI) IamDeleteGroups(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/groups/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeleteGroupsMembers calls DELETE /api/v1/iam/groups/{id}/members/{userId}: Delete a member.
func (a *GeneratedAPI) IamDeleteGroupsMembers(ctx context.Context, id string, userID string) (json.RawMessage, error) {
	path := "/api/v1/iam/groups/" + url.PathEscape(id) + "/members/" + url.PathEscape(userID)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeleteIdentityProviders calls DELETE /api/v1/iam/identity-providers/{id}: Delete an identity provider.
func (a *GeneratedAPI) IamDeleteIdentityProviders(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/identity-providers/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeleteInvites calls DELETE /api/v1/iam/invites/{id}: Delete an invite.
func (a *GeneratedAPI) IamDeleteInvites(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/invites/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeletePolicies calls DELETE /api/v1/iam/policies/{id}: Delete a policy.
func (a *GeneratedAPI) IamDeletePolicies(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/policies/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeletePolicyAttachments calls DELETE /api/v1/iam/policy-attachments/{id}: Delete a policy attachment.
func (a *GeneratedAPI) IamDeletePolicyAttachments(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/policy-attachments/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeleteRoles calls DELETE /api/v1/iam/roles/{id}: Delete a role.
func (a *GeneratedAPI) IamDeleteRoles(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/roles/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeleteServiceAccounts calls DELETE /api/v1/iam/service-accounts/{id}: Delete a service account.
func (a *GeneratedAPI) IamDeleteServiceAccounts(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/service-accounts/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamDeleteUsers calls DELETE /api/v1/iam/users/{id}: Delete an user.
func (a *GeneratedAPI) IamDeleteUsers(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/users/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// IamGroups calls GET /api/v1/iam/groups: List groups.
func (a *GeneratedAPI) IamGroups(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/groups", nil, nil)
}

// IamGroups2 calls GET /api/v1/iam/groups/{id}: Get a group.
func (a *GeneratedAPI) IamGroups2(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/groups/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// IamIdentityProviders calls GET /api/v1/iam/identity-providers: List identity providers.
func (a *GeneratedAPI) IamIdentityProviders(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/identity-providers", nil, nil)
}

// IamInvites calls GET /api/v1/iam/invites: List invites.
func (a *GeneratedAPI) IamInvites(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/invites", nil, nil)
}

// IamPolicies calls GET /api/v1/iam/policies: List policies.
func (a *GeneratedAPI) IamPolicies(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/policies", nil, nil)
}

// IamPolicies2 calls GET /api/v1/iam/policies/{id}: Get a policy.
func (a *GeneratedAPI) IamPolicies2(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/policies/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// IamPolicyAttachmentsArgs are the inputs of GeneratedAPI.IamPolicyAttachments.
type IamPolicyAttachmentsArgs struct {
	// PolicyID is "policyId" in the query.
	PolicyID *string `query:"policyId"`

	// PrincipalType is "principalType" in the query. One of: user, group, role, service_account.
	PrincipalType *string `query:"principalType"`

	// PrincipalID is "principalId" in the query.
	PrincipalID *string `query:"principalId"`
}

// IamPolicyAttachments calls GET /api/v1/iam/policy-attachments: List policy attachments.
func (a *GeneratedAPI) IamPolicyAttachments(ctx context.Context, p *IamPolicyAttachmentsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamPolicyAttachmentsArgs{}
	}
	q := url.Values{}
	if p.PolicyID != nil {
		q.Set("policyId", apigenQueryValue(*p.PolicyID))
	}
	if p.PrincipalType != nil {
		q.Set("principalType", apigenQueryValue(*p.PrincipalType))
	}
	if p.PrincipalID != nil {
		q.Set("principalId", apigenQueryValue(*p.PrincipalID))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/policy-attachments", q, nil)
}

// IamRoles calls GET /api/v1/iam/roles: List roles.
func (a *GeneratedAPI) IamRoles(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/roles", nil, nil)
}

// IamRoles2 calls GET /api/v1/iam/roles/{id}: Get a role.
func (a *GeneratedAPI) IamRoles2(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/roles/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// IamServiceAccounts calls GET /api/v1/iam/service-accounts: List service accounts.
func (a *GeneratedAPI) IamServiceAccounts(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/service-accounts", nil, nil)
}

// IamServiceAccounts2 calls GET /api/v1/iam/service-accounts/{id}: Get a service account.
func (a *GeneratedAPI) IamServiceAccounts2(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/service-accounts/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// IamUpdateIdentityProvidersArgs are the inputs of GeneratedAPI.IamUpdateIdentityProviders.
type IamUpdateIdentityProvidersArgs struct {
	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// Metadata is "metadata" in the body.
	Metadata map[string]any `json:"metadata,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamUpdateIdentityProviders calls PATCH /api/v1/iam/identity-providers/{id}: Update an identity provider.
func (a *GeneratedAPI) IamUpdateIdentityProviders(ctx context.Context, id string, p *IamUpdateIdentityProvidersArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamUpdateIdentityProvidersArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.Metadata != nil {
		payload["metadata"] = p.Metadata
	}
	path := "/api/v1/iam/identity-providers/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// IamUpdatePoliciesArgs are the inputs of GeneratedAPI.IamUpdatePolicies.
type IamUpdatePoliciesArgs struct {
	// Description is "description" in the body.
	Description *string `json:"description,omitempty"`

	// Document is "document" in the body.
	Document map[string]any `json:"document,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamUpdatePolicies calls PATCH /api/v1/iam/policies/{id}: Update a policy.
func (a *GeneratedAPI) IamUpdatePolicies(ctx context.Context, id string, p *IamUpdatePoliciesArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamUpdatePoliciesArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Description != nil {
		payload["description"] = *p.Description
	}
	if p.Document != nil {
		payload["document"] = p.Document
	}
	path := "/api/v1/iam/policies/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// IamUpdateUsersArgs are the inputs of GeneratedAPI.IamUpdateUsers.
type IamUpdateUsersArgs struct {
	// Role is "role" in the body. One of: owner, admin, member.
	Role *string `json:"role,omitempty"`

	// EmailVerified is "emailVerified" in the body.
	EmailVerified *bool `json:"emailVerified,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// IamUpdateUsers calls PATCH /api/v1/iam/users/{id}: Update an user.
func (a *GeneratedAPI) IamUpdateUsers(ctx context.Context, id string, p *IamUpdateUsersArgs) (json.RawMessage, error) {
	if p == nil {
		p = &IamUpdateUsersArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Role != nil {
		payload["role"] = *p.Role
	}
	if p.EmailVerified != nil {
		payload["emailVerified"] = *p.EmailVerified
	}
	path := "/api/v1/iam/users/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// IamUsers calls GET /api/v1/iam/users: List users.
func (a *GeneratedAPI) IamUsers(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/iam/users", nil, nil)
}

// IamUsersResetPassword calls POST /api/v1/iam/users/{id}/reset-password: Reset password an user.
func (a *GeneratedAPI) IamUsersResetPassword(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/iam/users/" + url.PathEscape(id) + "/reset-password"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// MfaChallengeArgs are the inputs of GeneratedAPI.MfaChallenge.
type MfaChallengeArgs struct {
	// Token is "token" in the query.
	Token any `query:"token"`
}

// MfaChallenge calls GET /api/v1/mfa/challenge: Read-only — lets the standalone /mfa page render the right input (authenticator vs. emailed code) regardless of which flow created the challenge.
func (a *GeneratedAPI) MfaChallenge(ctx context.Context, p *MfaChallengeArgs) (json.RawMessage, error) {
	if p == nil {
		p = &MfaChallengeArgs{}
	}
	q := url.Values{}
	if p.Token != nil {
		q.Set("token", apigenQueryValue(p.Token))
	}
	return a.c.apigenRequest(ctx, "GET", "/api/v1/mfa/challenge", q, nil)
}

// MfaDeleteDevices calls DELETE /api/v1/mfa/devices/{id}: Delete a device.
func (a *GeneratedAPI) MfaDeleteDevices(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/mfa/devices/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// MfaDevices calls GET /api/v1/mfa/devices: List devices.
func (a *GeneratedAPI) MfaDevices(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/mfa/devices", nil, nil)
}

// MfaEnrollArgs are the inputs of GeneratedAPI.MfaEnroll.
type MfaEnrollArgs struct {
	// Method is "method" in the body. One of: totp, email.
	Method *string `json:"method,omitempty"`

	// Label is "label" in the body.
	Label *string `json:"label,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// MfaEnroll calls POST /api/v1/mfa/enroll: Create an enroll.
func (a *GeneratedAPI) MfaEnroll(ctx context.Context, p *MfaEnrollArgs) (json.RawMessage, error) {
	if p == nil {
		p = &MfaEnrollArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Method != nil {
		payload["method"] = *p.Method
	}
	if p.Label != nil {
		payload["label"] = *p.Label
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/mfa/enroll", nil, payload)
}

// MfaResendCodeArgs are the inputs of GeneratedAPI.MfaResendCode.
type MfaResendCodeArgs struct {
	// MfaChallengeToken is "mfaChallengeToken" in the body, required.
	MfaChallengeToken string `json:"mfaChallengeToken"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// MfaResendCode calls POST /api/v1/mfa/resend-code: Create a resend code.
func (a *GeneratedAPI) MfaResendCode(ctx context.Context, p *MfaResendCodeArgs) (json.RawMessage, error) {
	if p == nil {
		p = &MfaResendCodeArgs{}
	}
	payload := apigenBody(p.Body)
	if p.MfaChallengeToken != "" {
		payload["mfaChallengeToken"] = p.MfaChallengeToken
	}
	if _, ok := payload["mfaChallengeToken"]; !ok {
		return nil, apigenMissing("MfaResendCode", "MfaChallengeToken")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/mfa/resend-code", nil, payload)
}

// MfaResendEnrollmentCodeArgs are the inputs of GeneratedAPI.MfaResendEnrollmentCode.
type MfaResendEnrollmentCodeArgs struct {
	// DeviceID is "deviceId" in the body, required.
	DeviceID string `json:"deviceId"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// MfaResendEnrollmentCode calls POST /api/v1/mfa/resend-enrollment-code: Create a resend enrollment code.
func (a *GeneratedAPI) MfaResendEnrollmentCode(ctx context.Context, p *MfaResendEnrollmentCodeArgs) (json.RawMessage, error) {
	if p == nil {
		p = &MfaResendEnrollmentCodeArgs{}
	}
	payload := apigenBody(p.Body)
	if p.DeviceID != "" {
		payload["deviceId"] = p.DeviceID
	}
	if _, ok := payload["deviceId"]; !ok {
		return nil, apigenMissing("MfaResendEnrollmentCode", "DeviceID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/mfa/resend-enrollment-code", nil, payload)
}

// MfaVerifyEnrollmentArgs are the inputs of GeneratedAPI.MfaVerifyEnrollment.
type MfaVerifyEnrollmentArgs struct {
	// DeviceID is "deviceId" in the body, required.
	DeviceID string `json:"deviceId"`

	// Code is "code" in the body.
	Code *string `json:"code,omitempty"`

	// TotpCode is "totpCode" in the body.
	TotpCode *string `json:"totpCode,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// MfaVerifyEnrollment calls POST /api/v1/mfa/verify-enrollment: Create a verify enrollment.
func (a *GeneratedAPI) MfaVerifyEnrollment(ctx context.Context, p *MfaVerifyEnrollmentArgs) (json.RawMessage, error) {
	if p == nil {
		p = &MfaVerifyEnrollmentArgs{}
	}
	payload := apigenBody(p.Body)
	if p.DeviceID != "" {
		payload["deviceId"] = p.DeviceID
	}
	if p.Code != nil {
		payload["code"] = *p.Code
	}
	if p.TotpCode != nil {
		payload["totpCode"] = *p.TotpCode
	}
	if _, ok := payload["deviceId"]; !ok {
		return nil, apigenMissing("MfaVerifyEnrollment", "DeviceID")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/mfa/verify-enrollment", nil, payload)
}

// MfaVerifyLoginArgs are the inputs of GeneratedAPI.MfaVerifyLogin.
type MfaVerifyLoginArgs struct {
	// MfaChallengeToken is "mfaChallengeToken" in the body, required.
	MfaChallengeToken string `json:"mfaChallengeToken"`

	// Code is "code" in the body, required.
	Code string `json:"code"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// MfaVerifyLogin calls POST /api/v1/mfa/verify-login: Create a verify login.
func (a *GeneratedAPI) MfaVerifyLogin(ctx context.Context, p *MfaVerifyLoginArgs) (json.RawMessage, error) {
	if p == nil {
		p = &MfaVerifyLoginArgs{}
	}
	payload := apigenBody(p.Body)
	if p.MfaChallengeToken != "" {
		payload["mfaChallengeToken"] = p.MfaChallengeToken
	}
	if p.Code != "" {
		payload["code"] = p.Code
	}
	if _, ok := payload["mfaChallengeToken"]; !ok {
		return nil, apigenMissing("MfaVerifyLogin", "MfaChallengeToken")
	}
	if _, ok := payload["code"]; !ok {
		return nil, apigenMissing("MfaVerifyLogin", "Code")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/mfa/verify-login", nil, payload)
}

// OidcClients calls GET /api/v1/oidc/clients: List clients.
func (a *GeneratedAPI) OidcClients(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/oidc/clients", nil, nil)
}

// OidcClientsRotateSecret calls POST /api/v1/oidc/clients/{id}/rotate-secret: Rotate secret a client.
func (a *GeneratedAPI) OidcClientsRotateSecret(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/oidc/clients/" + url.PathEscape(id) + "/rotate-secret"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// OidcCreateClientsArgs are the inputs of GeneratedAPI.OidcCreateClients.
type OidcCreateClientsArgs struct {
	// Name is "name" in the body, required.
	Name string `json:"name"`

	// RedirectURIs is "redirectUris" in the body.
	RedirectURIs []string `json:"redirectUris,omitempty"`

	// Scopes is "scopes" in the body.
	Scopes []string `json:"scopes,omitempty"`

	// Public is "public" in the body.
	Public *bool `json:"public,omitempty"`

	// LogoURL is "logoUrl" in the body.
	LogoURL *string `json:"logoUrl,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// OidcCreateClients calls POST /api/v1/oidc/clients: Create a client.
func (a *GeneratedAPI) OidcCreateClients(ctx context.Context, p *OidcCreateClientsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &OidcCreateClientsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != "" {
		payload["name"] = p.Name
	}
	if p.RedirectURIs != nil {
		payload["redirectUris"] = p.RedirectURIs
	}
	if p.Scopes != nil {
		payload["scopes"] = p.Scopes
	}
	if p.Public != nil {
		payload["public"] = *p.Public
	}
	if p.LogoURL != nil {
		payload["logoUrl"] = *p.LogoURL
	}
	if _, ok := payload["name"]; !ok {
		return nil, apigenMissing("OidcCreateClients", "Name")
	}
	return a.c.apigenRequest(ctx, "POST", "/api/v1/oidc/clients", nil, payload)
}

// OidcDeleteClients calls DELETE /api/v1/oidc/clients/{id}: Delete a client.
func (a *GeneratedAPI) OidcDeleteClients(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/oidc/clients/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "DELETE", path, nil, nil)
}

// OidcUpdateClientsArgs are the inputs of GeneratedAPI.OidcUpdateClients.
type OidcUpdateClientsArgs struct {
	// Name is "name" in the body.
	Name *string `json:"name,omitempty"`

	// RedirectURIs is "redirectUris" in the body.
	RedirectURIs []string `json:"redirectUris,omitempty"`

	// Scopes is "scopes" in the body.
	Scopes []string `json:"scopes,omitempty"`

	// LogoURL is "logoUrl" in the body.
	LogoURL *string `json:"logoUrl,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// OidcUpdateClients calls PATCH /api/v1/oidc/clients/{id}: Update a client.
func (a *GeneratedAPI) OidcUpdateClients(ctx context.Context, id string, p *OidcUpdateClientsArgs) (json.RawMessage, error) {
	if p == nil {
		p = &OidcUpdateClientsArgs{}
	}
	payload := apigenBody(p.Body)
	if p.Name != nil {
		payload["name"] = *p.Name
	}
	if p.RedirectURIs != nil {
		payload["redirectUris"] = p.RedirectURIs
	}
	if p.Scopes != nil {
		payload["scopes"] = p.Scopes
	}
	if p.LogoURL != nil {
		payload["logoUrl"] = *p.LogoURL
	}
	path := "/api/v1/oidc/clients/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "PATCH", path, nil, payload)
}

// OpsEndUsers calls GET /api/v1/ops/end-users: Workspace-scoped directory of end-users — people who have consented to an OIDC client owned by the active workspace.
func (a *GeneratedAPI) OpsEndUsers(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "GET", "/api/v1/ops/end-users", nil, nil)
}

// OpsEndUsers2 calls GET /api/v1/ops/end-users/{id}: Get an end user.
func (a *GeneratedAPI) OpsEndUsers2(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/ops/end-users/" + url.PathEscape(id)
	return a.c.apigenRequest(ctx, "GET", path, nil, nil)
}

// OpsEndUsersImpersonateArgs are the inputs of GeneratedAPI.OpsEndUsersImpersonate.
type OpsEndUsersImpersonateArgs struct {
	// DurationSeconds is "durationSeconds" in the body.
	DurationSeconds *int `json:"durationSeconds,omitempty"`

	// Body is the whole JSON body, for what the fields above do not cover; the fields
	// that are set replace its keys.
	Body map[string]any `json:"-"`
}

// OpsEndUsersImpersonate calls POST /api/v1/ops/end-users/{id}/impersonate: Impersonate an end user.
func (a *GeneratedAPI) OpsEndUsersImpersonate(ctx context.Context, id string, p *OpsEndUsersImpersonateArgs) (json.RawMessage, error) {
	if p == nil {
		p = &OpsEndUsersImpersonateArgs{}
	}
	payload := apigenBody(p.Body)
	if p.DurationSeconds != nil {
		payload["durationSeconds"] = *p.DurationSeconds
	}
	path := "/api/v1/ops/end-users/" + url.PathEscape(id) + "/impersonate"
	return a.c.apigenRequest(ctx, "POST", path, nil, payload)
}

// OpsEndUsersRevoke calls POST /api/v1/ops/end-users/{id}/revoke: Revoke an end user.
func (a *GeneratedAPI) OpsEndUsersRevoke(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/ops/end-users/" + url.PathEscape(id) + "/revoke"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// OpsEndUsersSendPasswordReset calls POST /api/v1/ops/end-users/{id}/send-password-reset: Send password reset an end user.
func (a *GeneratedAPI) OpsEndUsersSendPasswordReset(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/ops/end-users/" + url.PathEscape(id) + "/send-password-reset"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// OpsEndUsersStopImpersonation calls POST /api/v1/ops/end-users/stop-impersonation: Create a stop impersonation.
func (a *GeneratedAPI) OpsEndUsersStopImpersonation(ctx context.Context) (json.RawMessage, error) {
	return a.c.apigenRequest(ctx, "POST", "/api/v1/ops/end-users/stop-impersonation", nil, nil)
}

// OpsEndUsersVerifyEmail calls POST /api/v1/ops/end-users/{id}/verify-email: Verify email an end user.
func (a *GeneratedAPI) OpsEndUsersVerifyEmail(ctx context.Context, id string) (json.RawMessage, error) {
	path := "/api/v1/ops/end-users/" + url.PathEscape(id) + "/verify-email"
	return a.c.apigenRequest(ctx, "POST", path, nil, nil)
}

// apigenBody copies Body, so the fields set over it never change the caller's map.
func apigenBody(body map[string]any) map[string]any {
	out := make(map[string]any, len(body))
	for k, v := range body {
		out[k] = v
	}
	return out
}

// apigenQueryValue writes a query value the way the server reads it: strings as they are,
// numbers and booleans as JSON writes them, anything else as JSON.
func apigenQueryValue(v any) string {
	switch x := v.(type) {
	case string:
		return x
	case bool:
		return strconv.FormatBool(x)
	case int:
		return strconv.Itoa(x)
	case float64:
		return strconv.FormatFloat(x, 'f', -1, 64)
	}
	b, err := json.Marshal(v)
	if err != nil {
		return fmt.Sprint(v)
	}
	return string(b)
}

// apigenMissing is the error for a required body field that was neither set nor in Body.
func apigenMissing(method, field string) error {
	return fmt.Errorf("%s needs %s (or its key in Body)", method, field)
}
